(eval-when-compile    (require 'color-theme))

(defun my-charcoal-black ()
  "derived from charcoal-black"
  (color-theme-install
    '(my-charcoal-black
       (;;; Frame parameters
        (background-color . "gray5")
        (foreground-color . "gray")
        (background-mode . dark)
        (border-color . "yellow")
        (cursor-color . "grey")
        (mouse-color . "grey")
        )
       (;;; Variable definitions
        )
       ;;; Face definitions
       (font-lock-builtin-face ((t (:foreground "#0099ff"))))
       ;(font-lock-builtin-face ((t (:foreground "royal blue"))))
       (font-lock-comment-delimiter-face ((t (:foreground "slate gray"))))
       (font-lock-comment-face ((t (:foreground "slate gray"))))
       (font-lock-constant-face ((t (:foreground "deep sky blue"))))
       (font-lock-function-name-face ((t (:foreground "dodger blue"))))
       (font-lock-keyword-face ((t (:bold t :foreground "sky blue" :weight bold))))
       (font-lock-string-face ((t (:foreground "medium sea green"))))
       (font-lock-type-face ((t (:bold t :foreground "#00ff99" :weight bold))))
       (font-lock-variable-name-face ((t (:foreground "turquoise"))))

       (fringe ((t (:background "grey10"))))

       (mumamo-background-chunk-submode ((((class color) (min-colors 88) (background dark)) (:background "gray3"))))

       (py-builtins-face ((t (:foreground "lime green"))))
       (py-decorators-face ((t (:foreground "violet"))))
       (py-pseudo-keyword-face ((t (:foreground "pale green"))))
       (py-XXX-tag-face ((t (:foreground "salmon"))))
       )))

;(defun my-charcoal-black ()
;     ((help-highlight-face . underline)
;      (list-matching-lines-face . bold)
;      (mime-button-face . bold)
;      (mime-button-mouse-face . highlight)
;      (sgml-set-face . t)
;      (tags-tag-face . default)
;      (view-highlight-face . highlight)
;      (widget-mouse-face . highlight))
;     (default ((t (:stipple nil :background "black" :foreground "Grey" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 87 :width semi-condensed :family "misc-fixed"))))
;     (Info-title-1-face ((t (:bold t :weight bold :family "helv" :height 1.728))))
;     (Info-title-2-face ((t (:bold t :family "helv" :weight bold :height 1.44))))
;     (Info-title-3-face ((t (:bold t :weight bold :family "helv" :height 1.2))))
;     (Info-title-4-face ((t (:bold t :family "helv" :weight bold))))
;     (bold ((t (:bold t :weight bold))))
;     (bold-italic ((t (:bold t :foreground "beige" :weight bold))))
;     (border ((t (:background "Grey"))))
;     (calendar-today-face ((t (:underline t))))
;     (comint-highlight-input ((t (:bold t :weight bold))))
;     (comint-highlight-prompt ((t (:foreground "cyan"))))
;     (cursor ((t (:background "Grey"))))
;     (custom-button-face ((t (:foreground "gainsboro"))))
;     (custom-button-pressed-face ((t (:background "lightgrey" :foreground "black" :box (:line-width 2 :style pressed-button)))))
;     (custom-changed-face ((t (:background "blue" :foreground "white"))))
;     (custom-comment-face ((t (:background "dim gray"))))
;     (custom-comment-tag-face ((t (:foreground "gray80"))))
;     (custom-documentation-face ((t (:foreground "light blue"))))
;     (custom-face-tag-face ((t (:underline t))))
;     (custom-group-tag-face ((t (:bold t :foreground "pale turquoise" :weight bold))))
;     (custom-group-tag-face-1 ((t (:foreground "pale turquoise" :underline t))))
;     (custom-invalid-face ((t (:background "red" :foreground "yellow"))))
;     (custom-modified-face ((t (:background "blue" :foreground "white"))))
;     (custom-rogue-face ((t (:background "black" :foreground "pink"))))
;     (custom-saved-face ((t (:underline t))))
;     (custom-set-face ((t (:background "white" :foreground "blue"))))
;     (custom-state-face ((t (:foreground "light salmon"))))
;     (custom-variable-button-face ((t (:bold t :underline t :weight bold))))
;     (custom-variable-tag-face ((t (:bold t :foreground "turquoise" :weight bold))))
;     (diary-face ((t (:foreground "red"))))
;     (dired-face-directory ((t (:bold t :foreground "sky blue" :weight bold))))
;     (dired-face-executable ((t (:foreground "green yellow"))))
;     (dired-face-flagged ((t (:foreground "tomato"))))
;     (dired-face-marked ((t (:foreground "light salmon"))))
;     (dired-face-permissions ((t (:foreground "aquamarine"))))
;     (eshell-ls-archive-face ((t (:bold t :foreground "medium purple" :weight bold))))
;     (eshell-ls-backup-face ((t (:foreground "dim gray"))))
;     (eshell-ls-clutter-face ((t (:foreground "dim gray"))))
;     (eshell-ls-directory-face ((t (:bold t :foreground "medium slate blue" :weight bold))))
;     (eshell-ls-executable-face ((t (:bold t :foreground "aquamarine" :weight bold))))
;     (eshell-ls-missing-face ((t (:foreground "black"))))
;     (eshell-ls-picture-face ((t (:foreground "violet"))))
;     (eshell-ls-product-face ((t (:foreground "light steel blue"))))
;     (eshell-ls-readonly-face ((t (:foreground "aquamarine"))))
;     (eshell-ls-special-face ((t (:foreground "gold"))))
;     (eshell-ls-symlink-face ((t (:foreground "white"))))
;     (eshell-ls-unreadable-face ((t (:foreground "dim gray"))))
;     (eshell-prompt-face ((t (:bold t :foreground "light sky blue" :weight bold))))
;     (excerpt ((t (:italic t :slant italic))))
;     (fixed ((t (:bold t :weight bold))))
;     (fixed-pitch ((t (:family "courier"))))
;     (flyspell-duplicate-face ((t (:bold t :foreground "Gold3" :underline t :weight bold))))
;     (flyspell-incorrect-face ((t (:bold t :foreground "OrangeRed" :underline t :weight bold))))
;	 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;	 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;	 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;	 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;	 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;     (font-lock-builtin-face ((t (:foreground "SpringGreen"))))
;     (font-lock-comment-face ((t (:foreground "navajo white"))))
;     (font-lock-constant-face ((t (:foreground "pale green"))))
;     (font-lock-doc-face ((t (:foreground "light sky blue"))))
;     (font-lock-doc-string-face ((t (:foreground "salmon"))))
;     (font-lock-function-name-face ((t (:bold t :foreground "aquamarine" :weight bold))))
;     (font-lock-keyword-face ((t (:bold t :foreground "sky blue" :weight bold))))
;     (font-lock-reference-face ((t (:foreground "pale green"))))
;     (font-lock-string-face ((t (:foreground "cornflower blue"))))
;     (font-lock-type-face ((t (:bold t :foreground "sea green" :weight bold))))
;     (font-lock-variable-name-face ((t (:bold t :foreground "turquoise" :weight bold))))
;     (font-lock-warning-face ((t (:bold t :foreground "Red" :weight bold))))
;	 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;	 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;	 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;	 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;	 ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;     (fringe ((t (:background "black"))))
;     (header-line ((t (:box (:line-width -1 :style released-button) :background "grey20" :foreground "grey90" :box nil))))
;     (highlight ((t (:background "dark slate blue" :foreground "light blue"))))
;     (highline-face ((t (:background "DeepSkyBlue4"))))
;     (holiday-face ((t (:background "pink"))))
;     (info-header-node ((t (:bold t :weight bold))))
;     (info-header-xref ((t (:bold t :weight bold :foreground "sky blue"))))
;     (info-menu-5 ((t (:underline t))))
;     (info-menu-header ((t (:bold t :family "helv" :weight bold))))
;     (info-node ((t (:bold t :weight bold))))
;     (info-xref ((t (:bold t :foreground "sky blue" :weight bold))))
;     (isearch ((t (:background "slate blue"))))
;     (isearch-lazy-highlight-face ((t (:background "paleturquoise4"))))
;     (italic ((t (:foreground "sky blue"))))
;     (makefile-space-face ((t (:background "hotpink"))))
;     (menu ((t (:background "MidnightBlue" :foreground "Grey"))))
;     (message-cited-text-face ((t (:foreground "LightSalmon"))))
;     (message-header-cc-face ((t (:foreground "light cyan"))))
;     (message-header-name-face ((t (:foreground "LightBlue"))))
;     (message-header-newsgroups-face ((t (:italic t :bold t :foreground "MediumAquamarine" :slant italic :weight bold))))
;     (message-header-other-face ((t (:foreground "MediumAquamarine"))))
;     (message-header-subject-face ((t (:bold t :foreground "light cyan" :weight bold))))
;     (message-header-to-face ((t (:bold t :foreground "light cyan" :weight bold))))
;     (message-header-xheader-face ((t (:foreground "MediumAquamarine"))))
;     (message-mml-face ((t (:foreground "ForestGreen"))))
;     (message-separator-face ((t (:foreground "chocolate"))))
;     (mode-line ((t (:background "grey75" :foreground "black" :box (:line-width -1 :style released-button)))))
;     (mouse ((t (:background "Grey"))))
;     (region ((t (:background "DarkSlateBlue"))))
;     (scroll-bar ((t (:background "grey75"))))
;     (secondary-selection ((t (:background "steel blue"))))
;     (semantic-dirty-token-face ((t (:background "gray10"))))
;     (semantic-unmatched-syntax-face ((t (:underline "red"))))
;     (show-paren-match-face ((t (:background "light slate blue" :foreground "white"))))
;     (show-paren-mismatch-face ((t (:background "red" :foreground "white"))))
;     (speedbar-button-face ((t (:foreground "seashell2"))))
;     (speedbar-directory-face ((t (:foreground "seashell3"))))
;     (speedbar-file-face ((t (:foreground "seashell4"))))
;     (speedbar-highlight-face ((t (:background "dark slate blue" :foreground "wheat"))))
;     (speedbar-selected-face ((t (:foreground "seashell1" :underline t))))
;     (speedbar-separator-face ((t (:background "blue" :foreground "white" :overline "gray"))))
;     (speedbar-tag-face ((t (:foreground "antique white"))))
;     (tool-bar ((t (:background "grey75" :foreground "black" :box (:line-width 1 :style released-button)))))
;     (tooltip ((t (:background "lightyellow" :foreground "black"))))
;     (trailing-whitespace ((t (:background "red"))))
;     (underline ((t (:underline t))))
;     (variable-pitch ((t (:family "helv"))))
;     (widget-button-face ((t (:bold t :weight bold))))
;     (widget-button-pressed-face ((t (:foreground "red"))))
;     (widget-documentation-face ((t (:foreground "light blue"))))
;     (widget-field-face ((t (:background "RoyalBlue4" :foreground "wheat"))))
;     (widget-inactive-face ((t (:foreground "dim gray"))))
;     (widget-single-line-field-face ((t (:background "slate blue" :foreground "wheat"))))
;     (woman-bold-face ((t (:bold t :foreground "sky blue" :weight bold))))
;     (woman-italic-face ((t (:foreground "deep sky blue"))))
;     (woman-unknown-face ((t (:foreground "LightSalmon"))))
;     (zmacs-region ((t (:background "DarkSlateBlue")))))))
;
(add-to-list 'color-themes '(my-charcoal-black  "my-charcoal-black" "jeff balogh"))
(provide 'theme)
